// 02-Taro/demo-project/02-juanpi/src/pages/home/cpns/home-banner/index.jsx
import { memo } from 'react'
import { Swiper, SwiperItem, Image } from '@tarojs/components'
import PropTypes from 'proptypes'
import styles from './index.module.less'

const HomeBanner = memo(function (props) {
  const { banners } = props
  return (
    <Swiper
      className={styles['home-banner']}
      indicatorDots
      indicatorColor='#999'
      indicatorActiveColor='#ff464e'
      autoplay
      interval={3000}
    >
      {banners.map(item => (
        <SwiperItem key={item.id}>
          <Image className={styles['banner-img']} src={item.pic} mode='widthFix'></Image>
        </SwiperItem>
      ))}
    </Swiper>
  )
})

HomeBanner.propTypes = {
  banners: PropTypes.array
}

export default HomeBanner

// 01-uni-app/demo-project/02-shopping-street/pages/home/cpns/home-banner.vue
<template>
	<swiper class="banner" :indicator-dots="true" indicator-active-color="#ff8190" :autoplay="true" :interval="3000"
		:duration="1000">
		<template v-for="item of banners" :key="item.title">
			<swiper-item @click="onBannerItemClick(item)">
				<image class="image" :src="item.image" mode="widthFix"></image>
			</swiper-item>
		</template>
	</swiper>
</template>

<script setup>
	defineProps({
		banners: {
			type: Array,
			dafault: () => []
		}
	})
	
	const emit = defineEmits(['bannerItemClick'])
	
	const onBannerItemClick = banenrItem => {
		emit('bannerItemClick', banenrItem.link)
	}
</script>

<style lang="less">
	.banner {
		.image {
			width: 100%;
		}
	}
</style>
