// 01-uni-app/demo-project/01-hello-uniapp/pages/detail04/detail04.vue
<template>
	<view>
		<view class="item">item1</view>
		<view class="item">item2</view>
		<view class="item">item3</view>
		<view class="item">item4</view>
		<view class="item">item5</view>
		<view class="item">item6</view>
		<view class="item">item7</view>
		<view class="item">item8</view>
		<view class="item">item9</view>
		<view class="item">item10</view>
		<view class="item">item11</view>
		<view class="item">item12</view>
		<view class="item">item13</view>
		<view class="item">item14</view>
		<view class="item">item15</view>
		<view class="item">item16</view>
		<view class="item">item17</view>
		<view class="item">item18</view>
		<view class="item">item19</view>
		<view class="item">item20</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				msg: '哈哈'
			};
		},
		onLoad() {
			console.log('detail03 onLoad');
		},
		// 页面的生命周期。
		onShow() {
			console.log('detail04 onShow')
		},
		onReady() {
			console.log('detail04 onReady')
		},
		onHide() {
			console.log('detail04 onHide')
		},
		onUnload() {
			console.log('detail04 onUnload')
		},
		onPullDownRefresh() {
			console.log('detail04 onPullDownRefresh')
		},
		onReachBottom() {
			console.log('detail04 onReachBottom')
		},
		
		// 组件的生命周期
		/* beforeCreate() {
			console.log('detail04 beforeCreate')
		},
		created() {
			console.log('detail04 created')
		},
		beforeMount() {
			console.log('detail04 beforeMount')
		},
		mounted() {
			console.log('detail04 mounted')
		},
		beforeDestroy() {
			console.log('detail04 beforeDestroy')
		},
		destroyed() 
		console.log('detail04 destroyed'){} */
	}
</script>

<style lang="less">
.item {
	height: 200rpx;
	border-bottom: 2rpx solid red;
}
</style>

// 02-Taro/demo-project/01-hello-taro/src/pages/detail04/index.jsx
import { Component } from 'react'
import { View } from '@tarojs/components'
import Taro from '@tarojs/taro'
import './index.less'

export default class Detail04 extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  onLoad() {
    console.log("detail04 onLoad");
  }
  componentDidShow() {
    console.log("detail04 componentDidShow");
  }
  onReady() {
    console.log("detail04 onReady");
  }
  componentDidHide() {
    console.log("detail04 componentDidHide");
  }
  onUnload() {
    console.log("detail04 onUnload");
  }
  onPullDownRefresh() {
    console.log("detail04 onPullDownRefresh");
    setTimeout(() => {
      Taro.stopPullDownRefresh();
    }, 1000);
  }
  onReachBottom() {
    console.log("detail04 onReachBottom");
  }

  render () {
    return (
      <View className='detail04'>
        <View className='item'>item1</View>
        <View className='item'>item2</View>
        <View className='item'>item3</View>
        <View className='item'>item4</View>
        <View className='item'>item5</View>
        <View className='item'>item6</View>
        <View className='item'>item7</View>
        <View className='item'>item8</View>
        <View className='item'>item9</View>
        <View className='item'>item10</View>
        <View className='item'>item11</View>
        <View className='item'>item12</View>
        <View className='item'>item13</View>
        <View className='item'>item14</View>
        <View className='item'>item15</View>
      </View>
    )
  }
}
