// 02-Taro/demo-project/01-hello-taro/src/pages/home/index.jsx
import { Component } from 'react'
import { View, Navigator, Button } from '@tarojs/components'
import Taro from '@tarojs/taro'
import './index.less'

export default class Home extends Component {
  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  onLoad() {
    Taro.eventCenter.on('detail03ToHome', this.detail03ToHome)
  }

  onUnload() {
    Taro.eventCenter.off('detail03ToHome', this.detail03ToHome)
  }

  detail03ToHome(data) {
    console.log('home accept detail03 data:', data)
  }

  goToDetail01ByNavigate() {
    Taro.navigateTo({
      url: '/pages/detail01/index'
    })
  }

  goToDetail01ByRedirect() {
    Taro.redirectTo({
      url: '/pages/detail01/index'
    })
  }

  goToCategoryByNavigate() {
    Taro.switchTab({
      url: '/pages/category/index'
    })
  }

  getDetail01WithEventChannel() {
    Taro.navigateTo({
      url: '/pages/detail01/index?name=zzt&age=18',
      success(res) {
        if (process.env.TARO_ENV === 'weapp') {
          // 仅支持小程序
          res.eventChannel.emit('homeToDetail01', {
            data: 'home to detail01'
          })
        }
      }
    })
  }

  goToDetail02WithEventChannel() {
    Taro.navigateTo({
      url: '/pages/detail02/index',
      // 仅支持小程序
      events: {
        detail02ToHome(data) {
          console.log('home accept detail02 data:', data)
        }
      }
    })
  }

  goToDetail04() {
    Taro.navigateTo({
      url: '/pages/detail04/index'
    })
  }

  render() {
    return (
      <View className='home'>
        <View>1.页面跳转（组件）</View>
        <Navigator url='/pages/detail01/index' openType='navigate'>
          <Button>goToDetail01 navigate</Button>
        </Navigator>
        <Navigator url='/pages/detail01/index' openType='redirect'>
          <Button>goToDetail01 redirect</Button>
        </Navigator>
        <Navigator url='/pages/category/index' openType='switchTab'>
          <Button>goToCategory switchTab</Button>
        </Navigator>

        <View>2.页面跳转（API）</View>
        <Button onClick={() => this.goToDetail01ByNavigate()}>goToDetail01 navigate</Button>
        <Button onClick={() => this.goToDetail01ByRedirect()}>goToDetail01 redirect</Button>
        <Button onClick={() => this.goToCategoryByNavigate()}>goToCategory switchTab</Button>

        <View>3.页面传递数据（正向）</View>
        <Button onClick={() => this.getDetail01WithEventChannel()}>
          goToDetail01 eventChannel
        </Button>

        <View>4.页面传递数据（逆向）</View>
        <Button onClick={() => this.goToDetail02WithEventChannel()}>
          goToDetail02 eventChannel
        </Button>
        <Navigator url='/pages/detail03/index' openType='navigate'>
          <Button>goToDetail03 Taro.eventCenter</Button>
        </Navigator>

        <View>5.页面生命周期</View>
        <Navigator url='/pages/detail04/index' openType='navigate'>
          <Button>goToDetail04 class</Button>
        </Navigator>
        <Navigator url='/pages/detail05/index?name=zzt' openType='navigate'>
          <Button>goToDetail05 hook</Button>
        </Navigator>

        <View>6.网络请求和数据存储</View>
        <Navigator url='/pages/03-service/index' openType='navigate'>
          <Button>网络请求和数据存储</Button>
        </Navigator>
      </View>
    )
  }
}

// 01-uni-app/demo-project/01-hello-uniapp/pages/home/home.vue
<template>
  <view>
    <view>1.路由（组件）</view>
    <navigator url="/pages/detail01/detail01" open-type="navigate">
      <button>01-detail navigat</button>
    </navigator>

    <navigator url="/pages/detail01/detail01" open-type="redirect">
      <button>02-detail redirect</button>
    </navigator>

    <navigator url="/pages/category/category" open-type="switchTab">
      <button>03-category switchTab</button>
    </navigator>

    <view>2.路由（API）</view>
    <button @click="gotoDetail01ByNavigate">01-detail navigate</button>
    <button @click="gotoDetail01ByRedirect">02-detail redirect</button>
    <button @click="gotocategoryBySwitchTab">03-category switchTab</button>

    <view>3.页面传递参数（正向）</view>
    <navigator url="/pages/detail01/detail01?name=zzt&age=18" open-type="navigate">
      <button>01-detail navigate</button>
    </navigator>
    <button @click="goToDetail01WithEventChanelForward">01-detail EventChannel forward</button>

    <view>3.页面传递参数（逆向）</view>
    <button @click="gotoDetail02WithEventChannelReverse">01-detail02 EventChannel reverse</button>
    <button @click="goToDetail03WithEventBus">01-detail03 事件总线</button>

    <view>4.页面的生命周期</view>
    <button @click="goToDetail04">01-detail04 Option API</button>
    <button @click="goToDetail05">01-detail05 Composition API</button>

    <view>5.Composition API 页面传递参数（正向）</view>
    <button @click="gotoDetail06">01-detail06 navigate</button>

    <view>5.Composition API 页面传递参数（逆向）</view>
    <button @click="gotoDetail07">01-detail06 navigate</button>

    <view>5.Composition API 页面传递参数（全局事件总线）</view>
    <button @click="gotoDetail08">01-detail06 navigate</button>
  </view>
</template>

<script>
export default {
  data() {
    return {}
  },
  onLoad() {
    console.log('home onLoad')
    uni.$on('detail03ToHome', this.detail03ToHome)
  },
  onUnload() {
    console.log('home onUnload')
    uni.$off('detail03ToHome', this.detail03ToHome)
  },
  onShow() {
    console.log('home onShow')
  },
  onReady() {
    console.log('home onReady')
  },
  onHide() {
    console.log('home onHide')
  },
  onUnload() {
    console.log('home onUnload')
    uni.$off('acceptDataFromDetail03', this.acceptDataFromDetail03)
  },
  onPullDownRefresh() {
    console.log('home onPullDownRefresh')
  },
  onReachBottom() {
    console.log('home onReachBottom')
  },
  methods: {
    gotoDetail01ByNavigate() {
      uni.navigateTo({
        url: '/pages/detail01/detail01'
      })
    },
    gotoDetail01ByRedirect() {
      uni.redirectTo({
        url: '/pages/detail01/detail01'
      })
    },
    gotocategoryBySwitchTab() {
      uni.switchTab({
        url: '/pages/category/category'
      })
    },
    goToDetail01WithEventChanelForward() {
      uni.navigateTo({
        url: '/pages/detail01/detail01?name=zzt&age=18',
        success(res) {
          res.eventChannel.emit('homeSendToDetail01', {
            data: '我是从 Home 传递过来的！'
          })
        }
      })
    },
    gotoDetail02WithEventChannelReverse() {
      uni.navigateTo({
        url: '/pages/detail02/detail02?name=zzt&age=18',
        events: {
          detail02SendToHome(data) {
            console.log('detail02SendToHome data:', data)
          }
        }
      })
    },
    goToDetail03WithEventBus() {
      uni.navigateTo({
        url: '/pages/Detail03/Detail03'
      })
    },
    detail03ToHome(value) {
      console.log('home on detail03ToHome value:', value)
    },
    goToDetail04() {
      uni.navigateTo({
        url: '/pages/detail04/detail04'
      })
    },
    goToDetail05() {
      uni.navigateTo({
        url: '/pages/detail05/detail05'
      })
    },
    gotoDetail06() {},
    gotoDetail07() {},
    gotoDetail08() {}
  }
}
</script>

<style lang="scss"></style>
